
spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wxdemo
    username: root
    password: 123456wjf
